### ISSUE TITLE
Uncaught TypeError: Can't add property context, object is not extensible

### ISSUE THREAD

**Issue by shantp** [iam4x/react-btn-checkbox#1]
I tried using this with 0.13rc2 of react and I'm getting this error. Here's my code:

```javascript
import React from 'react';
import {Radio} from 'react-btn-checkbox';

class RadioApp extends React.Component {
  constructor(props){
    super(props);
    this.state = {
      'First': false,
      'Second': true,
      'Third': false
    }
  }
  render(){
    return (
      <Radio options={this.state} onChange={this.setState.bind(this)} />
    )
  }
}

React.render(<RadioApp />, document.getElementById("app"));
```

Also getting these warnings:

Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory
app.js:20318 Warning: Don't set the props property of the component. Mutate the existing props object instead.

Maybe this has to do with mixins in ES6?

**Comment by iam4x** [comment]
Hello @shantp 

Can you check with sourcemaps or unminified code? Because `app.js:20318` it's hard to know where does it comes :)

Seems more a problem with mutating props with your `super(props)` call!

Haven't tried `0.13` yet, gonna check this afternoon :)

**Comment by Spendar89** [comment]
It doesn't look like this was addressed... running into the same issue.

**Comment by x-light** [comment]
I'm getting the same as shantp too, same react version.

**Comment by StanOstapenko** [comment]
have the same issue

**Comment by iam4x** [comment]
Guys sorry for late update, can you test last release?

**Comment by x-light** [comment]
sure :)

**Comment by x-light** [comment]
Nice - its rendering without those errors now, thanks for fixing that up :+1:

**Comment by StanOstapenko** [comment]
Yep, works fine.

**Comment by iam4x** [comment]
Great
